In [1]:
import pyAgrum as gum
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os
import itertools

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import PolynomialFeatures
pd.set_option('display.max_rows', 250)

In [2]:
df = pd.read_csv("outputs/scores2.csv")
df

def normalize(col):
    # TODO: GROTER DAN WAT????
    if max(col) > 1:
        return col/max(col)
    return col

columns = ['items', 'nodes', 'timesteps', 'arcs_ratio', 'islands', 'values', 'nodestates', 'arcs', 'items/nodestates', 'items/arcs']
df[columns] = df[columns].apply(normalize)
df

,Unnamed: 0,items,nodes,timesteps,arcs_ratio,islands,values,algorithm,scorefunction,recall,...,fscore,dist2opt,tp,tn,fp,fn,nodestates,arcs,items/nodestates,items/arcs
0,0,0.1,0.5,0.333333,0.499999,1,0.5,3OFF2,AIC,0.666667,...,0.800000,0.333333,2,9,0,1,0.000244,0.1875,0.100000,0.1000
1,1,0.1,0.5,0.333333,0.499999,1,0.5,3OFF2,AIC,0.000000,...,0.000000,1.414214,0,7,2,3,0.000244,0.1875,0.100000,0.1000
2,2,0.1,0.5,0.333333,0.499999,1,0.5,3OFF2,AIC,0.000000,...,0.000000,1.414214,0,7,2,3,0.000244,0.1875,0.100000,0.1000
3,3,0.1,0.5,0.333333,0.499999,1,0.5,3OFF2,AIC,0.333333,...,0.400000,0.833333,1,8,1,2,0.000244,0.1875,0.100000,0.1000
4,4,0.1,0.5,0.333333,0.499999,1,0.5,3OFF2,AIC,0.000000,...,0.000000,1.414214,0,7,2,3,0.000244,0.1875,0.100000,0.1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129785,129785,1.0,1.0,1.000000,1.000000,1,1.0,TABU,K2,0.527273,...,0.495726,0.711878,29,464,33,26,1.000000,1.0000,0.000244,0.1875
129786,129786,1.0,1.0,1.000000,1.000000,1,1.0,TABU,K2,0.672727,...,0.587302,0.580023,37,463,34,18,1.000000,1.0000,0.000244,0.1875
129787,129787,1.0,1.0,1.000000,1.000000,1,1.0,TABU,K2,0.890909,...,0.830508,0.247555,49,483,14,6,1.000000,1.0000,0.000244,0.1875
129788,129788,1.0,1.0,1.000000,1.000000,1,1.0,TABU,K2,1.000000,...,0.880000,0.214286,55,482,15,0,1.000000,1.0000,0.000244,0.1875
129789,129789,1.0,1.0,1.000000,1.000000,1,1.0,TABU,K2,0.618182,...,0.485714,0.711186,34,446,51,21,1.000000,1.0000,0.000244,0.1875

In [3]:
dfhot = pd.get_dummies(df, columns=["algorithm","scorefunction"], dtype=int)
dfhot

,Unnamed: 0,items,nodes,timesteps,arcs_ratio,islands,values,recall,precision,fscore,...,algorithm_3OFF2,algorithm_HC,algorithm_MIIC,algorithm_MMHC,algorithm_TABU,scorefunction_AIC,scorefunction_BDEU,scorefunction_BIC,scorefunction_K2,scorefunction_L2L
0,0,0.1,0.5,0.333333,0.499999,1,0.5,0.666667,1.000000,0.800000,...,1,0,0,0,0,1,0,0,0,0
1,1,0.1,0.5,0.333333,0.499999,1,0.5,0.000000,0.000000,0.000000,...,1,0,0,0,0,1,0,0,0,0
2,2,0.1,0.5,0.333333,0.499999,1,0.5,0.000000,0.000000,0.000000,...,1,0,0,0,0,1,0,0,0,0
3,3,0.1,0.5,0.333333,0.499999,1,0.5,0.333333,0.500000,0.400000,...,1,0,0,0,0,1,0,0,0,0
4,4,0.1,0.5,0.333333,0.499999,1,0.5,0.000000,0.000000,0.000000,...,1,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129785,129785,1.0,1.0,1.000000,1.000000,1,1.0,0.527273,0.467742,0.495726,...,0,0,0,0,1,0,0,0,1,0
129786,129786,1.0,1.0,1.000000,1.000000,1,1.0,0.672727,0.521127,0.587302,...,0,0,0,0,1,0,0,0,1,0
129787,129787,1.0,1.0,1.000000,1.000000,1,1.0,0.890909,0.777778,0.830508,...,0,0,0,0,1,0,0,0,1,0
129788,129788,1.0,1.0,1.000000,1.000000,1,1.0,1.000000,0.785714,0.880000,...,0,0,0,0,1,0,0,0,1,0
129789,129789,1.0,1.0,1.000000,1.000000,1,1.0,0.618182,0.400000,0.485714,...,0,0,0,0,1,0,0,0,1,0

In [7]:
%%time
def powerset(iterable):
    "powerset([1,2,3]) --> () (1,) (2,) (3,) (1,2) (1,3) (2,3) (1,2,3)"
    s = list(iterable)
    combinations = list(itertools.chain.from_iterable(itertools.combinations(s, r) for r in range(1,len(s)+1)))
    
    merged = []
    for combination in combinations:
        merged.append(np.concatenate(combination, axis=None))
    return merged
    
item_c = ["items"]
nodes_c = ["nodes"]
arc_c = ["arcs_ratio"]
times_c = ["timesteps"]
values_c = ["values"]
algorithm_c = ["algorithm_3OFF2","algorithm_HC","algorithm_MIIC","algorithm_MMHC","algorithm_TABU"]
score_c = ["scorefunction_AIC","scorefunction_BDEU","scorefunction_BIC","scorefunction_K2","scorefunction_L2L"]
nodestates = ["nodestates"]
arcs = ["arcs"]
items_nodestates = ["items/nodestates"]
items_arcs = ["items/arcs"]

columns_c = [item_c, nodes_c, arc_c, times_c, values_c, algorithm_c, score_c, nodestates, arcs, items_nodestates, items_arcs]
column_sets = powerset(columns_c)

# column_sets = [["items","nodes","arcs_ratio","timesteps","values","algorithm_3OFF2","algorithm_HC","algorithm_MIIC","algorithm_MMHC","algorithm_TABU","scorefunction_AIC","scorefunction_BDEU","scorefunction_BIC","scorefunction_K2","scorefunction_L2L","nodestates","arcs","items/nodestates","items/arcs"]]

results3 = pd.DataFrame()

for c, columns in enumerate(column_sets[::-1]):
    X_train, X_test, y_train, y_test = train_test_split(dfhot[columns], dfhot["fscore"], test_size = 0.2)
    poly = PolynomialFeatures(degree=2)
    X_train_poly, X_test_poly = pd.DataFrame(poly.fit_transform(X_train), columns=poly.get_feature_names_out(X_train.columns)), pd.DataFrame(poly.fit_transform(X_test), columns=poly.get_feature_names_out(X_test.columns))

    regr = RandomForestRegressor()
    regr.fit(X_train_poly, y_train)
    results3 =  pd.concat([results3, pd.DataFrame({"items":["items" in columns], "nodes":["nodes" in columns], "arcs_ratio":["arcs_ratio" in columns], "timesteps":["timesteps" in columns], "values":["values" in columns], "algorithm":["algorithm_HC" in columns], "scorefunction":["scorefunction_AIC" in columns], "nodestates":["nodestates" in columns], "arcs":["arcs" in columns], "items/nodestates":["items/nodestates" in columns], "items/arcs":["items/arcs" in columns], "score":[regr.score(X_test_poly, y_test)]})], ignore_index=True)
    print(c/len(column_sets))
    
    break

results3

0.0
CPU times: total: 3min 54s
Wall time: 3min 55s

,items,nodes,arcs_ratio,timesteps,values,algorithm,scorefunction,nodestates,arcs,items/nodestates,items/arcs,score
0,True,True,True,True,True,True,True,True,True,True,True,0.38227

In [8]:
cm = sns.light_palette("red", as_cmap=True)

results3["items"] = results3["items"].astype(int)
results3["nodes"] = results3["nodes"].astype(int)
results3["arcs_ratio"] = results3["arcs_ratio"].astype(int)
results3["timesteps"] = results3["timesteps"].astype(int)
results3["values"] = results3["values"].astype(int)
results3["algorithm"] = results3["algorithm"].astype(int)
results3["scorefunction"] = results3["scorefunction"].astype(int)
results3["nodestates"] = results3["nodestates"].astype(int)
results3["arcs"] = results3["arcs"].astype(int)
results3["items/nodestates"] = results3["items/nodestates"].astype(int)
results3["items/arcs"] = results3["items/arcs"].astype(int)

results3.sort_values("score", ascending=False).to_csv("hotlinreg.csv")
display(results3[["items","nodes","arcs_ratio","timesteps","values","algorithm","scorefunction","nodestates","arcs","items/nodestates","items/arcs","score"]].sort_values("score", ascending=False).head().style.background_gradient(cmap='RdYlGn', vmin=0, vmax=1))
display(results3[["items","nodes","arcs_ratio","timesteps","values","algorithm","scorefunction","nodestates","arcs","items/nodestates","items/arcs","score"]].sort_values("score", ascending=False).tail().style.background_gradient(cmap='RdYlGn', vmin=0, vmax=1))

 # Feature Importances

In [9]:
feature_importance = pd.DataFrame({"feature":results3["features"][0],"importance":results3["importances"][0]})

feature_importance.sort_values(by="importance", ascending=False, key=abs).style.background_gradient(cmap='RdYlGn', vmin=-10, vmax=10)

KeyError: 'features'